spring:
  application:
    name: dynamic-mybatis-springboot-starter
druid:
  config:
    master: true
    jdbc-url: localhost:8080
    username: root
    password: 123456
    max-active: 10
    min-idle: 1
    max-wait-thread-count: 10
    stat-logger: true


