spring:
  application:
    name: dynamic-mybatis-springboot-starter
druid:
  config-map:
    master:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root123
      driver-class: com.mysql.jdbc.Driver
      initial-size: 1
      max-active: 8
      min-idle: 4
      validation-query: select 1
    slave:
      username: root
      driver-class: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test
      initial-size: 1
      max-active: 10
      min-idle: 5
      validation-query: select 1
